config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :books do
    get 'preview', on: :member
    resources :chapters do
      resources :sections
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: :true
  has_many :chapters
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :sections
  validates :title, presence: :true
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :chapter
  validates :title, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :fetch_book, only: [:show, :destroy, :edit, :update, :preview]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book= Book.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end

  end

  def edit

  end

  def update
    if @book.update_attributes(book_params)
      redirect_to book_path(@book)
    else
      render :edit
    end

  end

  def show

  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "Book #{@book.title} deleted succesfully"
  end

  def preview
    @chapters = @book.chapters.includes(:sections)
  end

  private
    def book_params
      params.require(:book).permit(:title,:description)
    end

    def fetch_book
      @book =Book.find(params[:id])
    end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :fetch_book
  before_action :fetch_chapter, only:[:show, :destroy, :edit, :update]
  def index
  end
  def new
    @chapter = @book.chapters.new
  end

  def create
   @chapter =  @book.chapters.new(chapter_params)

   if @chapter.save
     redirect_to book_chapter_path(@book, @chapter)
   else
     render :new
   end

  end

  def show
  end

  def edit

  end

  def update
    if @chapter.update_attributes(chapter_params)
      redirect_to book_chapter_path(@book, @chapter), notice: "chapter updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    redirect_to book_path(@book), notice: "Chapter deleted succesfully"

  end

  private
    def chapter_params
      params.require(:chapter).permit(:title, :notes)
    end

    def fetch_book
      @book = Book.find(params[:book_id])
    end

    def fetch_chapter
      @chapter = @book.chapters.find(params[:id])
    end


end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :fetch_chapter
  before_action :fetch_section, only: [:show, :edit, :update, :destroy]
  def index
  end

  def new
    @section = @chapter.sections.new
  end

  def create
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to book_chapter_section_path(@book, @chapter, @section),notice: "Section created succesfully"
    else
      render :new
    end
  end

  def show
  end
  def edit

  end
  def update
    if @section.update_attributes(section_params)
      redirect_to book_chapter_section_path(@book,@chapter,@section), notice: "Section updated succesfully"
    else
      render :edit
    end

  end

  def destroy
    @section.destroy
    redirect_to book_chapter_path(@book, @chapter), notice: "Section deleted succesfully"
  end


  private
    def fetch_chapter
      @book = Book.find(params[:book_id])
      @chapter = @book.chapters.find(params[:chapter_id])
    end

    def fetch_section
      @section = @chapter.sections.find(params[:id])

    end

    def section_params
      params.require(:section).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, placeholder: "Ex: How to learn code?" %>
  <%= f.input :description %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit book </h1>
  <%= @book.title %>
<%= render 'books/form'%>

app/views/books/index.html.erb
<div class="container">
  <%= link_to 'Add new book', new_book_path, class: "btn btn-primary" %>
  <p>List of Books to contribute</p>
  <div class="panel panel-default">
    <% @books.each do |book| %>
      <div class="panel-heading">
        <%= link_to "preview", preview_book_path(book) , class: "btn btn-primary btn-sm pull-right" %>
        <h3><%= link_to book.title, book_path(book) %></h3>

      </div>
      <div class="panel-body">
        <p><%= book.description %></p>
      </div>
    <% end %>

  </div>
</div>

app/views/books/new.html.erb
Add a new book
<%= render 'books/form'%>

app/views/books/preview.html.erb
<h1><%= @book.title %></h1>

<% @chapters.each do |chapter| %>
  <h2><%= chapter.title%> </h2>
    <% chapter.sections.each do |section| %>
      <h3><%= section.title %> </h3>
      <p><%= section.content %> </p>
    <% end %>
<% end %>

app/views/books/show.html.erb
<%= link_to "Delete", book_path(@book), method: :delete, class: "btn btn-danger btn-sm pull-right", data: {confirm: "Are you sure to delete the book?"}%>
<%= link_to "Edit", edit_book_path(@book), class: "btn btn-primary btn-sm pull-right"%>
<h1><%= @book.title %></h1>
<p><%= @book.description%></p>
<%= link_to "Add new Chapter", new_book_chapter_path(@book), class: "btn btn-success btn-sm pull-right" %>
<table class = "table table-striped table-hover">
  <% @book.chapters.each do |chapter|%>
  <tr>
    <td>
        <%= link_to chapter.title, book_chapter_path(@book,chapter)%>
    </td>
  </tr>
<%end%>
</table>

app/views/chapters/_form.html.erb
<%= simple_form_for [@book,@chapter] do |f| %>
  <%= f.input :title %>
  <%= f.input :notes%>
  <%= f.submit class: "btn btn-primary btn-large"%>
<% end %>

app/views/chapters/edit.html.erb
<h1>Edit chapter <%=@chapter.title%></h1>
<%= render 'chapters/form'%>

app/views/chapters/index.html.erb
<h1>Chapters#index</h1>
<p>Find me in app/views/chapters/index.html.erb</p>

app/views/chapters/new.html.erb
<h1>Add chapter to the book </h1>
<p><%=@book.title%></p>
<%= render 'chapters/form'%>

app/views/chapters/show.html.erb
<%= link_to "Delete", book_chapter_path(@book,@chapter), method: :delete, class: "btn btn-danger btn-sm pull-right", data: {confirm: "Are you sure to delete the chapter?"}%>
<%= link_to "Edit", edit_book_chapter_path(@book,@chapter), class: "btn btn-primary btn-sm pull-right"%>

<h1><%= @chapter.title %></h1
<small><%= @book.title %></small>
<%= link_to "Add new Section", new_book_chapter_section_path(@book, @chapter), class: "btn btn-success pull-right"%>

<table class = "table table-striped table-hover">
  <% @chapter.sections.each do |section|%>
  <tr>
    <td>
        <%= link_to section.title, book_chapter_path(@book,@chapter,section)%>
    </td>
  </tr>
<%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookAuthoring</title>
  <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application.js', 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">BookRite</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "All Books",books_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice]%>
    </div>
  <%end %>
  <%= yield %>
</div>



</body>
</html>

app/views/sections/_form.html.erb
<%= simple_form_for [@book,@chapter,@section] do |f| %>
<%= f.input :title %>
<%= f.input :content%>
<%= f.submit class:"btn btn-primary"%>
<% end %>

app/views/sections/edit.html.erb
<small><%= @book.title %> &gt; <%= @chapter.title%></small>
<h1>Edit section <%= @section.title %></h1>
<%= render 'sections/form'%>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/new.html.erb
<h1>Add new section to
  <%=@chapter.title%>
  <small><%= @book.title%></small>
</h1>
<%= render 'sections/form'%>

app/views/sections/show.html.erb
<%= link_to "Delete", book_chapter_section_path(@book,@chapter,@section), method: :delete, class: "btn btn-danger btn-sm pull-right", data: {confirm: "Are you sure to delete the section?"}%>
<%= link_to "Edit", edit_book_chapter_section_path(@book,@chapter,@section), class: "btn btn-primary btn-sm pull-right"%>

<small><%= @book.title %> &gt; <%= @chapter.title%></small>
<h1>  <%= @section.title %> </h1>

app/views/welcome/index.html.erb
<%= link_to 'Write a new book', new_book_path, class: "btn btn-primary btn-lg"%>